import type { TutorialDefinition } from '../types';

export const trafficLightTutorial: TutorialDefinition = {
  id: 'traffic-light',
  title: 'Traffic Light Controller',
  description: 'Build a working traffic light with 3 LEDs. Learn proper wiring — nothing works unless connected correctly!',
  difficulty: 'intermediate',
  estimatedMinutes: 12,
  steps: [
    {
      id: 'intro',
      title: 'Welcome!',
      content: 'Build a traffic light with Red, Green, and Blue LEDs. Each LED must be wired to a GPIO pin AND to ground — just like real electronics. If the wiring is wrong, the LEDs will NOT light up.',
      completionCondition: { type: 'manual' },
      tourTarget: 'canvas',
    },
    {
      id: 'add-breadboard',
      title: 'Step 1: Add a Breadboard',
      content: 'Open the **Parts** tab in the left sidebar and click **Add Breadboard** near the top.',
      completionCondition: { type: 'breadboard-added' },
      hints: ['The Add Breadboard button is at the top of the Parts tab.'],
      tourTarget: 'sidebar',
    },
    {
      id: 'add-red',
      title: 'Step 2: Place the Red LED',
      content: 'In the **Output** category, click **+** next to **Red LED**. Drag it onto the breadboard.',
      completionCondition: { type: 'component-placed', definitionId: 'led-red' },
      hints: ['LEDs are under the Output category in the sidebar.'],
      tourTarget: 'sidebar',
    },
    {
      id: 'add-green',
      title: 'Step 3: Place the Green LED',
      content: 'Click **+** next to **Green LED** and place it next to the red one.',
      completionCondition: { type: 'component-placed', definitionId: 'led-green' },
      tourTarget: 'sidebar',
    },
    {
      id: 'add-blue',
      title: 'Step 4: Place the Blue LED',
      content: 'Click **+** next to **Blue LED**. Now you have all three traffic light colors.',
      completionCondition: { type: 'component-placed', definitionId: 'led-blue' },
      tourTarget: 'sidebar',
    },
    {
      id: 'wire-red',
      title: 'Step 5: Wire the Red LED',
      content: 'Click **Wire** in the canvas toolbar. Connect:\n• GPIO17 (pin 11) → Red LED anode (+)\n• GND (pin 9) → Red LED cathode (−)',
      completionCondition: { type: 'wire-created' },
      hints: ['Each LED needs TWO wires — signal AND ground. Wire Mode button is in the canvas bottom toolbar.'],
      tourTarget: 'canvas',
    },
    {
      id: 'wire-others',
      title: 'Step 6: Wire Green and Blue',
      content: 'Continue wiring:\n• GPIO27 (pin 13) → Green LED anode + GND → cathode\n• GPIO22 (pin 15) → Blue LED anode + GND → cathode',
      completionCondition: { type: 'wire-created' },
      hints: ['GPIO27 is physical pin 13. GPIO22 is physical pin 15.'],
      tourTarget: 'canvas',
    },
    {
      id: 'load-code',
      title: 'Step 7: Load the Code',
      content: 'In the **Editor** tab, use the template dropdown to load **Traffic Light** starter code.',
      completionCondition: { type: 'code-contains', snippet: 'red' },
      hints: ['Editor tab → template dropdown at the top of the code editor.'],
      tourTarget: 'code-editor',
    },
    {
      id: 'run',
      title: 'Step 8: Run It!',
      content: 'Click **▶ Play**. LEDs cycle Red → Green → Blue. If any LED is dark, check its wiring — both GPIO and GND wires must be connected!',
      completionCondition: { type: 'simulation-started' },
      hints: ['If LEDs do not light up, check both the anode (GPIO) and cathode (GND) wires.'],
      tourTarget: 'run-btn',
    },
    {
      id: 'done',
      title: 'Congratulations! 🎉',
      content: 'You built a working traffic light! Key lesson: circuits only work when the loop is complete — signal from GPIO, through the component, back to ground. Try modifying the timing or adding a button to control the sequence.',
      completionCondition: { type: 'manual' },
      tourTarget: 'canvas',
    },
  ],
};
